# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_2st' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_2st

	pod 'RxSwift'
	pod 'RxCocoa'


end
